"""Write translations for medium-length JA chunks (100-500 chars) to chunk_registry."""
import sqlite3

DB = 'C:/Users/dissonance/Desktop/Trails/retrieval/index/trails.db'
conn = sqlite3.connect(DB)
c = conn.cursor()

translations = {
    'ja_chars:0313f573ded5': 'A private military company based in the Oredo Autonomous State.\n\nRizette Twining: Service concierge for Marduk Total Security. See #Rizette Twining.\n\n[Name unspecified]: Appearances: "Daybreak I", "Daybreak II" (G/B), "Trails beyond the Horizon" (S/B); Voice: Yuichiro Umehara; Head of security at Marduk Total Security. Nicknamed [unknown]. Considered the strongest jaeger in history.',

    'ja_chars:091ec76c5686': 'Melchior of the "Thorns": Caretaker of the Thorn Garden. See #Melchior.\n\nIx of the "Flash Bullets" (Iks Erdalion): Twin assassin affiliated with the Thorn Garden. See #Ix Erdalion.\n\nYolda of the "Shadow Eater" (Yolda Erdalion): Twin assassin affiliated with the Thorn Garden. See #Yolda Erdalion.',

    'ja_chars:11206': 'Cedric Reise Arnor: First-year student (Class I) at the main campus. See the Imperial Family section.\n\n[Name unspecified]: Appearances: "Cold Steel III", "Cold Steel IV", "Trails into Reverie"; Voice: Naomi Ozora; First-year student (Class I) at the main campus, who earned second place on the academy entrance exam. When considering enrollment, she also thought about attending Astraia Girls\' School, but chose Thors after hearing how its students distinguished themselves during the civil war.\n\n[Name unspecified]: Appearances: "Cold Steel III", "Cold Steel IV", "Trails into Reverie"; Voice: Junichi Yanagida; First-year student (Class I) at the main campus.',

    'ja_chars:1ce0d5dcc378_0': 'The equivalent of a military force within Crossbell, responsible for tasks including border security. The guards seen most frequently are those stationed at Bellguard Gate and Tangram Gate. Even new recruits assigned to the Security Force are considered elite — Lloyd and his team judged them formidable enough to engage without holding back. After Dieter became president and declared Crossbell\'s independence, the organization was renamed the "National Defense Army."',

    'ja_chars:1ce0d5dcc378_2': '[Name unspecified]: Appearances: "Trails from Zero", "Akatsuki no Kiseki"; The Security Force commander who never appears directly in the main story, whose name is not even revealed. A member of the pro-Empire faction in parliament. Near the end of the story, he makes contact with someone and is manipulated into triggering a catastrophe. Randy calls him "the idiot commander" and Noel refers to him as "that commander of ours" — neither holds him in any regard. He prioritizes appearances over substance, spending his time hosting guests with neither the competence nor the trust necessary for his position. In the story\'s final act, he is tricked into administering Gnosis to Security Force officers as a "health supplement," throwing not only the Security Force but all of Crossbell into chaos. The epilogue confirms he was dismissed. In "Akatsuki no Kiseki," his face and name are finally added. Spotted for his networking skills by Elfen Technologies, he was recruited and became an executive director there.',

    'ja_chars:224dcadda783_0': 'The supreme council of Ouroboros. Composed of seven members designated First through Seventh Pillar. Those beyond the ones listed here appear only in dialogue in "Sky the 3rd," "Trails to Azure," or "Cold Steel I," and their names remain unknown. They plan and direct various operations in service of the Grandmaster\'s Orpheus Final Plan.',

    'ja_chars:239d1c69e11d_0': 'Seven knight-puppet constructs created by the Gnomes as vessels to contain the Steel Sept-Terrion — born from the mingling of the Flame and Earth Sept-Terrions that once existed in the Empire — after the Witches divided and sealed the Steel within them. Throughout the Empire\'s hidden history, they appeared time and again, clashing with one another as rehearsals for the Seven Rivalries of the coming Great Twilight. Each of the seven possesses a distinct individual consciousness with unique specialties and innate abilities, though they are not all of equal power. In Alberich\'s assessment, excluding the anomalous Black, the Gold and Silver are particularly outstanding; the Vermillion, which served as the Demon King\'s vessel, comes next; the remaining Gray, Blue, and Violet are roughly equal. Ordinarily, each construct forms a contract with someone who overcomes its trials in the proving grounds, granting the title of Awakener (Riser). Exceptions exist: the Vermillion can only be awakened by those of the Imperial Arnor bloodline, while the Violet favors unconventional candidates and holds its final trial in an unusual manner. All seven frames are composed of Zemurian Ore.',

    'ja_chars:27ed10b12bb1_2': 'Prior to the Hamel Tragedy, he was also the mastermind who employed rogue jaegers to attack the Osborne estate — killing Osborne\'s wife Kasha and leaving Rean severely wounded. During the Hundred Days War, he led the vanguard at the outbreak of hostilities, commanding the 13th Armored Division in an assault on Haken Gate. He survived until the ceasefire, but was secretly court-martialed upon returning home on charges of the Hamel village massacre and its cover-up, and executed in private. A timid man, his wife had left him and he had raised Reclert alone. In his final letter to Reclert, written just before his execution, he addressed words to his son alongside regret over what he had done and bewilderment over "how he could have been so tempted."',

    'ja_chars:45a919faba46': 'Estelle Bright, Joshua Bright: Protagonists of "Sky FC" and "Sky SC." See #Estelle Bright and #Joshua Bright.\n\nKevin Graham: Protagonist of "Sky the 3rd." See #Kevin Graham.\n\nLloyd Bannings: Protagonist of "Trails from Zero," "Trails to Azure," and "Trails into Reverie." See #Lloyd Bannings.\n\nRean Schwarzer: Protagonist of the "Trails of Cold Steel" series and "Trails into Reverie." See #Rean Schwarzer.\n\nRufus Albarea: Protagonist of "Trails into Reverie." See #Rufus Albarea and #C.\n\nNacht Weiss, Chloe Barnett: Protagonists of "Akatsuki no Kiseki." See Eiyuu Densetsu: Akatsuki no Kiseki#Protagonists.\n\nVan Arkride: Protagonist of "Trails through Daybreak" and "Trails beyond the Horizon." See #Van Arkride.\n\nLavian Winslet: Protagonist of the anime "Trails of Cold Steel: Northern War." See Eiyuu Densetsu: Trails of Cold Steel#TV Anime.',

    'ja_chars:6814aee69193': 'Scenario Books / Scenario Collections: [bibliography list]\n\nNote: In addition to settings not explicitly established in the main game, cases where story information may be missed depending on branching choices have also been included in the "secondary sources" category above, citing scenario books where possible.\n\nSetting Materials / Mooks: [bibliography list — includes PS4 Cold Steel IV limited edition bonus items]\n\nNovels: [list]\nManga: [list]\nMagazines: [list]\nOther: [list]',

    'ja_chars:6c2a66564c73': '[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Ryo Sugisaki; Inspector in the Special Investigations Division of the Calvard Capital Police.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Masayuki Sato; Investigator in the Special Investigations Division of the Calvard Capital Police.',

    'ja_chars:6fba9bed53d6_0': 'The highest-ranking agents of Ouroboros, personally chosen by the Grandmaster. Each possesses combat prowess and resourcefulness far beyond ordinary humans, backed by varied and often dark personal histories. They primarily act as the hands and feet of the Anguis and do not hold a role in proposing strategy. However, they operate without restrictions, and face no organizational sanction even if their actions happen to hinder the Orpheus Final Plan. As a result, characters such as Joshua, Ren, and Sharon occasionally appear as playable allies who cooperate with the protagonists depending on the installment.\n\nTo be selected as an Enforcer, combat ability is required — but so is carrying some form of darkness within one\'s heart.',

    'ja_chars:856dc6233100': '[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Kikuko Inoue; A direct disciple of Dr. C. Epstein and one of the "Three Disciples" alongside Dr. Russell and Dr. Schmidt. Holds an honorary professorship at the Basel Institute of Science. From the very inception of the orbment, she foresaw that its adoption would eventually produce a technological gap between regions, and has maintained the belief that outlying areas are precisely where orbments are most needed. Acting on this conviction, she organized outreach delegations — requesting Bracer escorts — to promote technology development in remote regions, laying the groundwork for widespread distribution.\n\nQuatre Salision: A researcher in the master\'s program at the Basel Institute of Science, and one of Hamilton\'s students. See #Quatre Salision.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Hisashige Araki; CEO of the Verne Company. Also serves on the board of directors of the Basel Institute of Science.',

    'ja_chars:88d593fbab5c': 'A mafia organization operating in the shadows of the Calvard Republic.\n\n[Name unspecified]: Appearances: "Daybreak I" (B); Voice: Tomokazu Seki; Leader of Almata.\n\n[Name unspecified]: Appearances: "Daybreak I" (B), "Trails beyond the Horizon" (B); Voice: Shota Aoi; One of Almata\'s three executives.\n\n[Name unspecified]: Appearances: "Daybreak I" (B), "Trails beyond the Horizon" (B); Voice: Nozomi Yamamoto; One of Almata\'s three executives.\n\n[Name unspecified]: Appearances: "Daybreak I" (B), "Trails beyond the Horizon" (B); Voice: Tarusuke Shingaki; One of Almata\'s three executives.',

    'ja_chars:8992eccb931f': 'A high-ranking jaeger corps based in the Northern Free City Zone, with many former military personnel among its ranks.\n\n[Name unspecified]: Appearances: "Daybreak I" (B), "Daybreak II"; Voice: Anna Kitamoto; Company commander of Eisenschilt.\n\n[Name unspecified]: Appearances: "Trails through Daybreak" (B); Voice: Takahisa Uchino; Regimental commander of Eisenschilt.',

    'ja_chars:8f398bbf4bab': 'Judith Ranster: One of the top-tier actresses. See #Judith Ranster.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Reina Ueda; Young actress.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Tsuyoshi Koyama; Film director affiliated with Vegas Film.\n\n[Name unspecified]: Appearances: "Daybreak I"; Voice: Yoshinori Kitajima; President of Vegas Film.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Masami Seto; The elder of a pair of dancer sisters active in Saad.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Nozomi Yamamoto; The younger of a pair of dancer sisters active in Saad.\n\n[Name unspecified]: Appearances: "Daybreak II," "Trails beyond the Horizon"; Voice: Kimiko Saito, Reiho Kuratomo (childhood); A chanson singer who was once enormously popular, and the grandmother of actress Judith.',

    'ja_chars:98a04b3a4403': 'The knightly order maintained by the Septian Church. They have clashed with Ouroboros time and again throughout hidden history, and the two organizations regard each other as sworn enemies. Across all series entries, they join forces with or provide support to the protagonists and are involved in the story in some capacity.',

    'ja_chars:9a4603244e37_0': 'An elite cadre drawn from within the order itself, comprising twelve members in all. Appointment requires the manifestation of a Stigma. The Stigma is inscribed into one\'s deep consciousness; releasing it allows one to draw out true power — a power capable of overwhelming not only humans but demons.',

    'ja_chars:a167f26d3d87_0': 'A major theater troupe based in Crossbell\'s entertainment district. Tickets sell out almost instantly and are notoriously difficult to obtain; however, Mayor McDougall has been a long-standing fan and maintains a close relationship with the troupe. From the director to every performer, all are artists utterly possessed by the "demon" of theater, and their devotion to the craft is absolute.',

    'ja_chars:b442674d525e_2': 'Her weapon is a Temple Sword — the same type as Liese\'s. She primarily attacks by slashing enemies while wreathing the blade in flame. Like Liese\'s, the blade can extend and retract and be broken apart and launched as projectiles; Scarlett additionally wields a technique that envelops it in fire.\n\n"C" (Cee): Leader of the Imperial Liberation Front. Clad in a black mask and mantle, operating in the shadows with the aim of bringing down Osborne. Highly capable — when first appearing before Class VII, C simultaneously engaged Rean, Laura, and Fie without yielding ground, a display said to rival Instructor Sara and Instructor Neithardt in raw ability. True identity: [a student at Thors Military Academy — withheld to avoid spoilers]. Weapon: a relic from the dark ages.',

    'ja_chars:b57159b862da': 'A jaeger corps that primarily operated in the autonomous territories surrounding the Erebonian Empire. Responsible for the "Guild Serial Attack Incident," they were destroyed by a joint counter-offensive between the Bracer Guild and the Imperial Army — a plan devised by Cassius.\n\n[Name unspecified]: Appearances: "Akatsuki no Kiseki"; Former unit commander of the Jester Jaeger Corps. Harbors a grudge against Cassius, whose plan led to the corps\' destruction. He formed a contract with the rival corps Nidhoggr and planned a large-scale terrorist attack using "Phaia" bombs during the Queen\'s birthday celebration in the Kingdom of Liberl, intending to plunge the kingdom into chaos. His true aim was to assassinate Cassius during the accompanying martial arts tournament; he and his remaining followers disguised themselves as tournament entrants. His cover was blown by Nacht\'s quick thinking, and his pride was turned against him — Kingdom soldiers disguised as spectators entrapped him, and he was captured by a single blow from Yuria. This deepened his hatred of Cassius. While imprisoned in Leiston Fortress, he refused to pay Nidhoggr their fee and was subsequently killed by Airy.',

    'ja_chars:c1a6f592f1cd_2': 'Before coming to Crossbell, she lived in Ruan, Liberl, and attended Jenis Royal Academy — but due to poor health, she repeatedly missed school, took leaves of absence, and returned. After the resolution of the Liberl Ark incident, she underwent advanced surgical treatment at Remiferia and recovered. Her desire to repay the city of Crossbell — where she was hospitalized at St. Ursula Medical College during treatment — combined with her admiration for the heroes who resolved the Liberl Ark incident, led her to pursue a career as a Bracer. Her hobbies include reading, and combined with what she learned at the Royal Academy, she has extensive knowledge of world affairs, law, and business terminology. As a result, she and Nacht complement each other\'s weaknesses not only in temperament but in areas of expertise.\n\nThough she appears full of energy as described above, she occasionally reveals "a side completely unlike that persona" — a quality that calls a certain someone to mind.\n\nHer weapon is a one-handed sword, but she has never trained under any master; her style is entirely self-taught, mimicking techniques she read about in novels. Despite this, she habitually confronts criminals without regard for the gap in ability, keeping her restraint-minded partner Nacht in constant exasperation. Her tenacity has earned even Nacht\'s acknowledgment, however, and she continues to refine her skills through rigorous training from senior Bracers Curtz and Wenzel.',

    'ja_chars:cfa7baeafa52': 'An autonomous state located in the west-central part of the continent. Home to the headquarters of the Epstein Foundation and the Bracer Guild.\n\n[Name unspecified]: Appearances: none (mentioned by reference only); Voice: Makoto Sahara; Deceased — never appears directly in the main story. Approximately fifty years before the era of the games (around S.E. 1150), he invented the orbment, triggering the technological revolution known as the Orbal Revolution. He passed away in S.E. 1154, shortly after the invention. His legacy was carried on by the Epstein Foundation — established in S.E. 1155 in the Lamare Autonomous State — and by his three great disciples. The orbment gradually spread and transformed the world in unprecedented ways. In his lifetime, he foresaw the emergence of a future technological singularity, leaving behind the words: "A self-improving intelligence that surpasses humanity — once that threshold is reached, the advance of technology will escape human hands. For better or worse, it will bring about a transformation in human society unlike anything seen before."\n\nRoberts: Epstein Foundation specialist in orbal networks. See #Roberts.',

    'ja_chars:d7aab53a637f_2': '[Name unspecified]: Appears as a rival to Mishy [note: new character debuted June S.E. 1206]. A mechanical fake-Mishy who genuinely believes itself to be real. It is later revealed that this character is in fact Mishy\'s brother, believed to have died in childhood, and that its name is Mishnaider.',

    'ja_chars:ed0944787db4': 'Branches are located in five major cities including the royal capital Grancel, each overseeing operations in the surrounding region. [Note: Full Bracers are authorized for international activity by default regardless of branch affiliation, with no geographic restriction on their area of operation. Junior Bracers operate under the supervision of their branch and are restricted to the region that branch covers.] Advancement from Junior Bracer to full Bracer requires letters of recommendation from all five branches.',

    'ja_chars:eebb0023db17': 'Sena Dirk: Appearances: "Trails through Daybreak" (name only), "Trails beyond the Horizon"; Voice: unknown; A woman active in the early 1100s S.E. Together with artist Aramis, officer Atkinson, and philosopher Auguste, she co-founded the Revolutionary Liberation Army.\n\nAramis Gainsbourg: Appearances: "Trails through Daybreak" (name only); An artist who co-led the revolution alongside Sena.\n\nUrgar Atkinson: Appearances: "Trails through Daybreak" (name only); A young military officer who co-led the revolution alongside Sena.\n\nAuguste Aldan: Appearances: "Trails through Daybreak" (name only), "Daybreak II" (B); A philosopher who co-led the revolution alongside Sena.\n\nLagun Khan: Appearances: "Trails beyond the Horizon" (B); Voice: Shunsuke Takeuchi; A man who once controlled the Radiant Capital [JA: 煌都] forty years prior.',

    'ja_chars:f7f57026ef78_1': 'Jimmy is currently an accountant in Ruan. He was formerly a merchant trader, but in order to cover his daughter Chloe\'s medical expenses, he sold both his business and his previous home to make ends meet.\n\n[Name unspecified]: Appearances: "Trails beyond the Horizon"; Voice: Kosuke Kuwano; Contract employee at R&A Security.',

    'ja_chars:fc04edc93439': 'A high school founded by the artist Aramis, who played a central role in the democratic revolution.\n\nAgnes Claudel: A female student at Aramis High School. See #Agnes Claudel.\n\nRenne Bright: Student council president of Aramis High School. See #Renne Bright.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Soma Saito; A student at Aramis High School and childhood friend of Agnes.\n\n[Name unspecified]: Appearances: "Trails through Daybreak," "Trails beyond the Horizon"; Voice: Kanae Ito; A student at Aramis High School and childhood friend of Agnes.',

    'ja_chars:fd3de0613323_0': 'One of the jaeger corps that operated in the western part of the Zemurian continent. A group of specialists led by the cunning corps chief Rutger — considered, alongside the Red Constellation, one of the two strongest corps on the continent. However, after Rutger and Red Constellation chief Baldur Orlando mutually killed each other in combat, the remaining members dispersed with only former member Fie remaining. The corps has not formally disbanded; according to Xeno and Leonidas, the survivors are working toward "reclaiming the commander."\n\nThe reading of the corps name "Zephyr" (西風 / West Wind) was originally pronounced "seifuu" when first spoken aloud in "Zero Evolution," but changed to "nishikaze" in Cold Steel I and all subsequent titles.',

    'ja_chars:fd3de0613323_2': 'Background: Born in a remote area of central-eastern Zemuria, from a warrior clan whose territory was rich in Septium ore. When an arms merchant attacked the settlement with heavy forces to seize the ore, Rutger and Garcia saved the village from disaster; in gratitude, [he] pledged lifelong loyalty to Rutger to repay the clan\'s debt. From the time [he] first appears in the main story of "Cold Steel I" onward, [he] acts in constant partnership with Xeno. Since their histories are substantially shared from that point, subsequent history is covered in the #Xeno entry.\n\nGarcia Rossi: Former unit commander of Zephyr, now serving as chief lieutenant (division head) of the Rubache Trading Company after leaving the corps. See #Garcia Rossi.',
}

for chunk_id, translation in translations.items():
    c.execute('UPDATE chunk_registry SET translated_content = ? WHERE chunk_id = ?', (translation, chunk_id))

conn.commit()
print(f'Updated {len(translations)} chunks')

c.execute("SELECT COUNT(*) FROM chunk_registry WHERE language='ja' AND translated_content IS NOT NULL")
print(f'Total translated so far: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM chunk_registry WHERE language='ja' AND (translated_content IS NULL OR translated_content='')")
print(f'Remaining untranslated: {c.fetchone()[0]}')
conn.close()
