<?php
# This file was generated by the MediaWiki 1.41.5 installer and customized
# for the Trails Database backend.

if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = "Trails Database";
$wgMetaNamespace = "Trails_Database";

$wgScriptPath = "";
$wgServer = "http://localhost:8080";
$wgResourceBasePath = $wgScriptPath;

$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

$wgEnableEmail = false;
$wgEnableUserEmail = false;
$wgEnotifUserTalk = false;
$wgEnotifWatchlist = false;
$wgEmailAuthentication = false;

# Database settings
$wgDBtype = "mysql";
$wgDBserver = "127.0.0.1";
$wgDBname = "trails_wiki";
$wgDBuser = "wiki_user";
$wgDBpassword = "trailsdb2026";

$wgDBprefix = "";
$wgDBssl = false;
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
$wgSharedTables[] = "actor";

$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

$wgEnableUploads = false;
$wgUseInstantCommons = false;
$wgPingback = false;

$wgLanguageCode = "en";
$wgLocaltimezone = "UTC";

$wgSecretKey = "f37f3bd23be5f49edfbebc4f62c3e4daaab280fc46d076bd8fe72b1238a993d2";
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = "fca700758acb0ea9";

$wgRightsPage = "";
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

$wgDiff3 = "/usr/bin/diff3";
$wgDefaultSkin = "vector-2022";

wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# =============================================================================
# Trails Database — custom configuration
# =============================================================================

# Disable public registration (private single-user wiki)
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['read'] = true;

# ---------------------------------------------------------------------------
# Custom namespaces
# ---------------------------------------------------------------------------
define( 'NS_METADATA',      100 );
define( 'NS_METADATA_TALK', 101 );
define( 'NS_DRAFT',         102 );
define( 'NS_DRAFT_TALK',    103 );
define( 'NS_SCHEMA',        104 );
define( 'NS_SCHEMA_TALK',   105 );

$wgExtraNamespaces[NS_METADATA]      = 'Metadata';
$wgExtraNamespaces[NS_METADATA_TALK] = 'Metadata_talk';
$wgExtraNamespaces[NS_DRAFT]         = 'Draft';
$wgExtraNamespaces[NS_DRAFT_TALK]    = 'Draft_talk';
$wgExtraNamespaces[NS_SCHEMA]        = 'Schema';
$wgExtraNamespaces[NS_SCHEMA_TALK]   = 'Schema_talk';

$wgNamespacesToBeSearchedDefault[NS_DRAFT] = false;

# ---------------------------------------------------------------------------
# Extensions
# ---------------------------------------------------------------------------
wfLoadExtension( 'Cargo' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'PageSchemas' );
wfLoadExtension( 'Scribunto' );
# ApprovedRevs requires MW 1.42+ — deferred until upgrade
# wfLoadExtension( 'ApprovedRevs' );
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'TemplateData' );

# Scribunto
$wgScribuntoDefaultEngine = 'luastandalone';

# AbuseFilter (structural integrity only)
$wgAbuseFilterActions['block'] = false;
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['*']['abusefilter-view'] = false;

# ---------------------------------------------------------------------------
# Cargo DB connection
# ---------------------------------------------------------------------------
$wgCargoDBtype     = 'mysql';
$wgCargoDBserver   = '127.0.0.1';
$wgCargoDBname     = 'trails_wiki';
$wgCargoDBuser     = 'wiki_user';
$wgCargoDBpassword = 'trailsdb2026';
